"""add seen tables

Revision ID: cef392d26e63
Revises: 7f682532afa2
Create Date: 2020-10-16 15:43:16.898117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef392d26e63'
down_revision = '7f682532afa2'
branch_labels = None
depends_on = None


def upgrade():
    # Add seen tables
    op.create_table('seen_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('journalist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_seen_files_file_id_files')),
    sa.ForeignKeyConstraint(['journalist_id'], ['users.id'], name=op.f('fk_seen_files_journalist_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seen_files')),
    sa.UniqueConstraint('file_id', 'journalist_id', name=op.f('uq_seen_files_file_id'))
    )
    op.create_table('seen_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('journalist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journalist_id'], ['users.id'], name=op.f('fk_seen_messages_journalist_id_users')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_seen_messages_message_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seen_messages')),
    sa.UniqueConstraint('message_id', 'journalist_id', name=op.f('uq_seen_messages_message_id'))
    )
    op.create_table('seen_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('journalist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journalist_id'], ['users.id'], name=op.f('fk_seen_replies_journalist_id_users')),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], name=op.f('fk_seen_replies_reply_id_replies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seen_replies')),
    sa.UniqueConstraint('reply_id', 'journalist_id', name=op.f('uq_seen_replies_reply_id'))
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seen_replies')
    op.drop_table('seen_messages')
    op.drop_table('seen_files')
    # ### end Alembic commands ###
